### ISSUE TITLE
Find good seeds for games

### ISSUE THREAD

**Issue by raylfli** [CSC207-UofT/course-project-the-losers-club#129]
- War: ~~1111111 (32 moves)~~ does not work with fixed implementation

**Comment by azamat-khamidov** [comment]
Seed for Bura: 12345
Card choice sequence : {6H, 7C, KH, 9D, 8D, 8H, AC, QH, 9C, 9H, 10H, 10S, JC, 7S, 9S, AH, AS, 8C}
The game ends with the second player winning after the aforementioned sequence

**Comment by raylfli** [comment]
Demo is over, seeds no longer necessary.
